### ISSUE TITLE
wuffs-c requires clang-format-5.0

### ISSUE THREAD

**Issue by mvdan** [google/wuffs#10]
Is there a reason why version 5.0 is explicitly required? I only have `clang-format` installed (version 6.0), and creating a symlink in my $PATH keeps wuffs-c running normally.

I presume that the tool is used to format the C output from the generator. Why not make it configurable though? It could, for example, default to `clang-format`, where one could change it to `clang-format-5.0` or any other desired version.

**Comment by nigeltao** [comment]
*Why is an explicit version required? Why clang-format-5.0 and not just clang-format?*

In the Wuffs repo (but not your repo), everything checked in under `gen/c` is clang-formatted. Different versions of clang-format will format the same C code differently. While the `gen/c` changes in https://github.com/google/wuffs/commit/abdf46045f1e7dd5d3a51ccdcc0f58ebbad8b96c are possibly a clang-format bug, it does illustrate my point. Without an explicit version, two people (or the same person working on two different systems) could cause spurious edits (and edit-revert wars) when checking in their changes.

*Why version 5.0? Why not 4.0 or 6.0?*

It's somewhat arbitrary, but 5.0 seemed a reasonable compromise of being not too old and not too new, as of today. A future change will undoubtedly bump 5.0 to something higher, whether 5.x or y.0.

**Comment by nigeltao** [comment]
Having said that, it'd be possible to make it configurable...
