### ISSUE TITLE
A way to overflow or underflow on purpose

### ISSUE THREAD

**Issue by mvdan** [google/wuffs#16]
Sometimes it is really wanted. All I could find in the repo is:

    doc/wuffs-the-language.md:74:TODO: ignore-overflow ops, equivalent to Swift's `&+`.

I presume that means it is planned?

**Comment by nigeltao** [comment]
This is already implemented. `x ~mod+ y` will add while ignoring overflow. There's also the `x ~mod+= y` form that's analogous to the `+=` operator. An example of its use is in `std/adler32/common_adler32.wuffs`. There, it's not as though the overflow

It's a little verbose, but breaking it down:
- the `~` means an overflow-concious operator.
- the `mod` says overflow is treated as modular arithmetic (the `sat` form chooses saturating arithmetic).
- the `+` means, y'know, plus.
