### ISSUE TITLE
Decode JPEG

### ISSUE THREAD

**Issue by nigeltao** [google/wuffs#42]
There should be a `std/jpeg` package.

**Comment by nigeltao** [comment]
Some feature work remains to do (to support the relatively uncommon progressive JPEGs, the relatively rare RGB and CMYK JPEGs and possibly even rarer variants such as 12-bit JPEGs). And triangle-filter upsampling still needs doing to reach output parity with libjpeg-turbo. And there's lots of optimization work to do. But overall, Wuffs has a working end-to-end JPEG decoder (that's now fuzz-tested), so I'm going to close the "Decode JPEG" issue as Fixed.

**Comment by syoyo** [comment]
:+1:
