### ISSUE TITLE
example/{imageviewer,sdl-imageviewer} don't work/work wrong with DefaultDepth 30

### ISSUE THREAD

**Issue by pjanx** [google/wuffs#51]
System: Arch Linux, X11 with DefaultDepth 30
Tested on various PNG images.

sdl-imageviewer always crashes, because `SDL_GetWindowSurface()` returns NULL.

imageviewer garbles the images it manages to display in the following way:
![image](https://user-images.githubusercontent.com/40222273/125551868-07187c7b-7905-4bb4-9413-791458ba6ee4.png)

On slightly larger images, it crashes on `xcb_wait_for_event()` returning NULL.

**Comment by pjanx** [comment]
```
diff --git a/example/sdl-imageviewer/sdl-imageviewer.cc b/example/sdl-imageviewer/sdl-imageviewer.cc
index 6d2b0fec..76819716 100644
--- a/example/sdl-imageviewer/sdl-imageviewer.cc
+++ b/example/sdl-imageviewer/sdl-imageviewer.cc
@@ -229,6 +229,10 @@ bool g_load_via_sdl_image = false;
 bool  //
 draw(SDL_Window* window) {
   SDL_Surface* ws = SDL_GetWindowSurface(window);
+  if (!ws) {
+    fprintf(stderr, "draw: SDL_GetWindowSurface(): %s\n", SDL_GetError());
+    return false;
+  }
   SDL_FillRect(ws, NULL, SDL_MapRGB(ws->format, 0x00, 0x00, 0x00));
   if (g_image) {
     SDL_BlitSurface(g_image, NULL, ws, NULL);
```
gives me the somewhat expected:
```
draw: SDL_GetWindowSurface(): Unknown window pixel format
```

**Comment by pjanx** [comment]
SDL can be made to work in the following manner, which even seems to be an acceptable patch as-is:
```
diff --git a/example/sdl-imageviewer/sdl-imageviewer.cc b/example/sdl-imageviewer/sdl-imageviewer.cc
index 6d2b0fec..1464c94c 100644
--- a/example/sdl-imageviewer/sdl-imageviewer.cc
+++ b/example/sdl-imageviewer/sdl-imageviewer.cc
@@ -229,6 +229,15 @@ bool g_load_via_sdl_image = false;
 bool  //
 draw(SDL_Window* window) {
   SDL_Surface* ws = SDL_GetWindowSurface(window);
+  if (!ws) {
+    SDL_Renderer *r = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);
+    SDL_Texture *texture = SDL_CreateTextureFromSurface(r, g_image);
+    SDL_RenderCopy(r, texture, nullptr, nullptr);
+    SDL_RenderPresent(r);
+    SDL_DestroyTexture(texture);
+    SDL_DestroyRenderer(r);
+    return true;
+  }
   SDL_FillRect(ws, NULL, SDL_MapRGB(ws->format, 0x00, 0x00, 0x00));
   if (g_image) {
     SDL_BlitSurface(g_image, NULL, ws, NULL);
```

**Comment by pjanx** [comment]
Feel free to close my issue once SDL works (just handle the failing `SDL_GetWindowSurface`), XCB rejected my attempts at debugging, and it's a horrible mess all around.

**Comment by nigeltao** [comment]
Thanks for the bug report. Can you copy/paste the output of `xdpyinfo`?

Or, if that's too large, perhaps `xdpyinfo | head -n 100`?

> System: Arch Linux, X11 with DefaultDepth 30

Just double-checking... is it really 30, not 32?

**Comment by pjanx** [comment]
It's just 10-bit colour. [xdpyinfo.log](https://github.com/google/wuffs/files/6818523/xdpyinfo.log) doesn't contain alpha, so it isn't all that useful.

Here is an [XGB image viewer](https://github.com/google/wuffs/files/6818564/xgb-image-30bit.go.txt) for a known-to-work approach, with XRender scaling, although it's set up to require the depth--you could have two serialising functions, one for ARGB24, another for RGB30. As a side note, I explicitly disclaim all copyrights for my works in this issue, it's on the edge of applicability anyway.

**Comment by pjanx** [comment]
Coming back with randomly acquired knowledge. The issue with the XCB demo is trivial: `DecodeImageCallbacks::SelectPixfmt` virtual-defaults to `WUFFS_BASE__PIXEL_FORMAT__BGRA_PREMUL`, and the `xcb_image_t` is hardcoded to use `s->root_depth` and completely disregards the Visual. The XRender extension could be used to resolve the difference within X.org, similarly to the way it's used in that Go code--this is the simplest fix for this issue, together with the SDL workaround.
