### ISSUE TITLE
PNG decoder should be able to read out eXIf

### ISSUE THREAD

**Issue by pjanx** [google/wuffs#59]
https://ftp-osl.osuosl.org/pub/libpng/documents/pngext-1.5.0.html#C.eXIf

I've found all of 25 such images amongst thousands, but they exist.

**Comment by nigeltao** [comment]
Can you upload or link to an example PNG-with-EXIF file?

**Comment by nigeltao** [comment]
See also:
https://github.com/w3c/PNG-spec/issues/28

**Comment by pjanx** [comment]
Of course, here you are! https://derpicdn.net/img/view/2020/10/3/2458529.png
