### ISSUE TITLE
__get_cpuid_count was not declared in this scope

### ISSUE THREAD

**Issue by MichaelLi-y** [google/wuffs#74]
What is the reason for ： error: ‘__get_cpuid_count’ was not declared in this scope ，It's in this fail:wuffs-v0.3.c

**Comment by nigeltao** [comment]
What C compiler are you using (and what version is it)? What's your Operating System and what CPU architecture are you running on?

**Comment by MichaelLi-y** [comment]
C compiler is visual studio code(1.6.42),operating system is ubuntu16.04 and my cpu architecture is x86_64 .
