### ISSUE TITLE
Is methods calling other methods supported?

### ISSUE THREAD

**Issue by mvdan** [google/wuffs#8]
Whatever I try, I always hit errors like `cannot convert Wuffs call "this.advance?(src:in.src)" to C`. This leads me to the TODO in the Wuffs source code:

```
// TODO: fix this.
//
// This might involve calling g.writeExpr with replaceNothing??
return fmt.Errorf("cannot convert Wuffs call %q to C", n.Str(g.tm))
```

The code in question was the following:

```
pri struct backBitReader?(
        rem u32,
        cur u8,
        curbits u8[..8],
)

pri func backBitReader.advance?(src reader1)() {
        if this.rem == 0 {
                return error "TODO"
        }
        this.rem -= 1
        this.cur = in.src.read_u8?()
        this.curbits = 8
}

pri func backBitReader.skipPadding?(src reader1)() {
        this.advance?(src:in.src)
}
```

Am I missing something, or is this simply not supported yet?

**Comment by nigeltao** [comment]
It's simply not supported yet. The gen.writeCallSuspendibles method in statement.go is full of hard coded hacks at the moment. Sorry.

**Comment by mvdan** [comment]
Ah, that's unfortunate. It's going to be hard to write any non-trivial piece of code if I can't go beyond a single function body.

Is this up in your TODO list? Can I help in any way?

**Comment by mvdan** [comment]
Oh, I didn't mean to shame you into getting this done faster - I understand this is a side project, and also a very early stage one.

I also don't think it's that early for me to use it. After all, I'm not expecting to get something usable or stable in the short term. My repository is more of an experiment to play with.

In any case, looking forward to having function calls working :)

**Comment by mvdan** [comment]
Thanks so much for this! It was definitely the number one reason blocking me from implementing anything non-trivial.
