### ISSUE TITLE
lib/readerat: delayed invalid seek offset detected?

### ISSUE THREAD

**Issue by detaoin** [google/wuffs#80]
Hi,

I was reading the code, out of curiosity, and it seems to me that the conditional test that checks whether the seek offset is negative misses this case (it will be detected by the next call to ReadAt).

https://github.com/google/wuffs/blob/b8d44be7835a373633e7cf0987978d4a5733fcf5/lib/readerat/readerat.go#L90

should be
```
if offset < 0 {
```
instead?

**Comment by nigeltao** [comment]
You're right. Thanks for the bug report.
