### ISSUE TITLE
Add a "hello world outside of std" example 

### ISSUE THREAD

**Issue by mvdan** [google/wuffs#9]
If anyone wants to play with Wuffs today, it's fairly safe to assume they'd want the code to live somewhere outside of the `std` directory. Forking and symlinks are a possibility, but they're not a very comfortable way to do things.

I propose that we add a simple example of what a working Wuffs program would be. For example, a dead simple program that you can compile to a working binary:

* A `capitalize.wuffs` file, that takes a stream of bytes, and converts all lowercase `a` letters to `A`, before writing to an output stream
* A `main.c` file, that uses the func/type from Wuffs above and puts it in between stdin and stdout
* A `Makefile` or script that, using `wuffs-c` and `$CC`, generates the C code and compiles a working executable

In total, this should all be under 50 lines of code. Yet it would be a great starting point for those wanting to try something of their own with Wuffs.

Split from #4 - there I mentioned how it took me some digging through the Wuffs codebase to figure out how to make it work outside of the `std` directory.

**Comment by nigeltao** [comment]
It's a valid feature request, although it (and the general concept of "write better docs and examples, for newbies or otherwise") probably isn't the highest priority while Wuffs (the language) and wuffs (the command line tool) are both yet to be stabilized.

**Comment by mvdan** [comment]
That's a good point. We can keep this issue as a reminder for once the language and tools have stabilized some more.
